services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "goAppTasksDB"
            PGDATA: "/var/lib/postgresql/data/goAppTasksDB/"
        ports:
            - "5432:5432"
        volumes:
            - ./migrations/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
            - pgdata:/var/lib/postgresql/data/goAppTasksDB
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d goAppTasksDB"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: "postgres"
            DB_PASSWORD: "admin"
            DB_NAME: "goAppTasksDB"
        depends_on:
            db:
                condition: service_healthy
volumes:
    pgdata: